module.exports = {
    "team_abbr": {
        "arizona": "ARI",
        "cardinals": "ARI",
        "arizona cardinals": "ARI",
        "atlanta": "ATL",
        "falcons": "ATL",
        "atlanta falcons": "ATL",
        "baltimore": "BAL",
        "ravens": "BAL",
        "baltimore ravens": "BAL",
        "buffalo": "BUF",
        "bills": "BUF",
        "buffalo bills": "BUF",
        "carolina": "CAR",
        "panthers": "CAR",
        "carolina panthers": "CAR",
        "chicago": "CHI",
        "bears": "CHI",
        "chicago bears": "CHI",
        "cincinnati": "CIN",
        "bengals": "CIN",
        "cincinnati Bengals": "CIN",
        "cleveland": "CLE",
        "browns": "CLE",
        "cleveland browns": "CLE",
        "dallas": "DAL",
        "cowboys": "DAL",
        "dallas cowboys": "DAL",
        "denver": "DEN",
        "broncos": "DEN",
        "denver broncos": "DEN",
        "detroit": "DET",
        "lions": "DET",
        "detroit lions": "DET",
        "green bay": "GB",
        "packers": "GB",
        "green bay packers": "GB",
        "houston": "HOU",
        "texans": "HOU",
        "houston texans": "HOU",
        "indianapolis": "IND",
        "colts": "IND",
        "indianapolis colts": "IND",
        "jacksonville": "JAX",
        "jaguars": "JAX",
        "jacksonville jaguars": "JAX",
        "kansas city": "KC",
        "chiefs": "KC",
        "kansas city chiefs": "KC",
        "chargers": "LAC",
        "los angeles chargers": "LAC",
        "rams": "LAR",
        "los angeles rams": "LAR",
        "miami": "MIA",
        "dolphins": "MIA",
        "miami dolphins": "MIA",
        "minnesota": "MIN",
        "vikings": "MIN",
        "minnesota vikings": "MIN",
        "new england": "NE",
        "patriots": "NE",
        "new england patriots": "NE",
        "new orleans": "NO",
        "saints": "NO",
        "new orleans saints": "NO",
        "giants": "NYG",
        "new york giants": "NYG",
        "jets": "NYJ",
        "new york jets": "NYJ",
        "oakland": "OAK",
        "raiders": "OAK",
        "oakland raiders": "OAK",
        "philadelphia": "PHI",
        "eagles": "PHI",
        "philadelphia eagles": "PHI",
        "pittsburgh": "PIT",
        "steelers": "PIT",
        "pittsburgh steelers": "PIT",
        "san francisco": "SF",
        "40 niners": "SF",
        "forty-niners": "SF",
        "san francisco 40 niners": "SF",
        "san francisco forty-niners": "SF",
        "seattle": "SEA",
        "seahawks": "SEA",
        "c hawks": "SEA",
        "seattle seahawks": "SEA",
        "tampa bay": "TB",
        "buccaneers": "TB",
        "tampa bay buccaneers": "TB",
        "tennessee": "TEN",
        "titans": "TEN",
        "tennessee titans": "TEN",
        "washington": "WAS",
        "redskins": "WAS",
        "washington redskins": "WAS"
    },
    "team_name": {
        "ARI": "arizona cardinals",
        "ATL": "atlanta falcons",
        "BAL": "baltimore ravens",
        "BUF": "buffalo Bills",
        "CAR": "carolina panthers",
        "CHI": "chicago bears",
        "CIN": "cincinnati bengals",
        "CLE": "cleveland browns",
        "DAL": "dallas cowboys",
        "DEN": "denver broncos",
        "DET": "detroit lions",
        "GB": "green bay packers",
        "HOU": "houston texans",
        "IND": "indianapolis colts",
        "JAX": "jacksonville jaguars",
        "KC": "kansas city chiefs",
        "LAC": "los angeles chargers",
        "LAR": "los angeles rams",
        "MIA": "miami dolphins",
        "MIN": "minnesota vikings",
        "NE": "new england patriots",
        "NO": "new orleans saints",
        "NYG": "new york giants",
        "NYJ": "new york jets",
        "OAK": "oakland raiders",
        "PHI": "philadelphia eagles",
        "PIT": "pittsburgh steelers",
        "SEA": "seattle seahawks",
        "SF": "san francisco forty-niners",
        "TB": "tampa bay buccaneers",
        "TEN": "tennessee titans",
        "WAS": "washington redskins"
    },
    "team_city": {
        "ARI": "arizona",
        "ATL": "atlanta",
        "BAL": "baltimore",
        "BUF": "buffalo",
        "CAR": "carolina",
        "CHI": "chicago",
        "CIN": "cincinnati",
        "CLE": "cleveland",
        "DAL": "dallas",
        "DEN": "denver",
        "DET": "detroit",
        "GB": "green bay",
        "HOU": "houston",
        "IND": "indianapolis",
        "JAX": "jacksonville",
        "KC": "kansas city",
        "LAC": "los angeles",
        "LAR": "los angeles",
        "MIA": "miami",
        "MIN": "minnesota",
        "NE": "new england",
        "NO": "new orleans",
        "NYG": "new york",
        "NYJ": "new york",
        "OAK": "oakland",
        "PHI": "philadelphia",
        "PIT": "pittsburgh",
        "SEA": "seattle",
        "SF": "san francisco",
        "TB": "tampa bay",
        "TEN": "tennessee",
        "WAS": "washington"
    },
    "years": {
        "2002": "twenty_two",
        "2003": "twenty_three",
        "2004": "twenty_four",
        "2005": "twenty_five",
        "2006": "twenty_six",
        "2007": "twenty_seven",
        "2008": "twenty_eight",
        "2009": "twenty_nine",
        "2010": "twenty_ten",
        "2011": "twenty_eleven",
        "2012": "twenty_twelve",
        "2013": "twenty_thirteen",
        "2014": "twenty_fourteen",
        "2015": "twenty_fifteen",
        "2016": "twenty_sixteen",
        "2017": "twenty_seventeen"
    }
};